config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  get 'home' , to: 'home#index'

  #Print Document
    # ปริ้นสามแถว
    get '/outbounds/:id/print/destination' , to: 'prints#show_destination' , as: 'prints_destination'
    get '/outbounds/:id/print/origin' , to: 'prints#show_origin' , as: 'prints_origin'
    # ปริ้นแถวเดียว
    get 'outbounds/:id/print/paper_destination' , to: 'prints#paper_show_destination' , as: 'paper_destination'
    get 'outbounds/:id/print/paper_origin' , to: 'prints#paper_show_origin' , as: 'paper_origin'

    # ปริ้น internals
    get '/internals/:id/print/internal' , to: 'prints#paper_internal' , as: 'paper_internal'

  get 'bags/' , to: 'bags#index'
  resources :bags
  resources :parcels
  resources :feedbacks
  resources :outbounds do
  	resources :bags
  end
  resources :internals do
    resource :parcels
  end
end

app/models/outbound.rb
class Outbound < ApplicationRecord
  has_many :bags , dependent: :destroy

  def self.search(search)
  	if search.blank?
  		Outbound.all
  	else
  		Outbound.where('outbound_number LIKE ?', "%#{search}%")
  	end
  end

  def name_check
  	if self.name != nil
  		return self.name
  	else
  		return "-"
  	end
  end

  def count
    self.bags.count
  end

  def check_remark
    if self.remark != nil
      return self.remark
    else
      return "-"
    end
  end
end

app/controllers/outbounds_controller.rb
class OutboundsController < ApplicationController
  require 'will_paginate/array'
  def index
    @outbounds = Outbound.search(params[:search]).paginate(page: params[:page], per_page: 12).order(created_at: :desc)
  end

  def new
    @outbound = Outbound.new
  end

  def create
    @outbound = Outbound.create(outbound_params)
    if @outbound.save
      flash[:complete] = "ป.58 เลขที่ #{@outbound.outbound_number} ได้ถูกสร้างแล้ว ชื่อผู้สร้าง #{@outbound.name}"
      redirect_to new_outbound_bag_path(@outbound.id)
    else
      render 'new'
    end
  end

  def show
    @outbound = Outbound.find(params[:id])
    # Sort bag number by destination  with model method
    @bags = Bag.where(outbound_id: @outbound).sort_by(&:destination).paginate(page: params[:page], per_page: 20)
    respond_to do |format|
      format.html
      format.pdf do
        render template: 'outbounds/report',
        pdf: 'report',
        page_size: 'A4'
      end
    end
  end

  def destroy
    @outbound = Outbound.find(params[:id])
    if @outbound.destroy
      flash[:destroy] = "ป.58 เลขที่ #{@outbound.outbound_number} ได้ถูกลบแล้ว"
      redirect_to outbounds_path
    end
  end

  private
    def outbound_params
      params.require(:outbound).permit(:origin , :destination , :sent_date , :strap , :car , :outbound_number , :name , :remark)
    end
end

app/helpers/outbounds_helper.rb
module OutboundsHelper
end

app/views/outbounds/_form.html.erb
<%= form_for @outbound do |form| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
          <%= form.label :เลขที่เอกสาร , class: 'label-control' %>
          <%= form.text_field :outbound_number , class: ' form-control' , value: Time.now.strftime('%d%m%y')+rand(00000..99999).to_s , readonly: true %>
      </div>
      <div class="form-group">
          <%= form.label :ต้นทาง , class: 'label-control'%>
          <%= form.text_field :origin , class:'form-control' , placeholder: 'กรุณาระบุต้นทาง' , required: true %>
      </div>
      <div class="form-group">
          <%= form.label :ปลายทาง , class: 'label-control'%>
          <%= form.text_field :destination , class: 'form-control', placeholder: 'กรุณาระบุปลายทาง' , required: true  %>
      </div>
      <div class="form-group">
        <%= form.label :ชื่อผู้สร้าง , class: 'label-control' %>
        <%= form.text_field :name , class:'form-control' , required: true , placeholder: 'โปรดระบุชื่อ-สกุล เพื่อใช้ในการตรวจสอบ' %>
      </div>
      <div class="form-group">
        <%= form.label :เลขที่สายรัด , class: 'label-control' %>
        <%= form.text_field :strap , class:'form-control' , required: true , value: "-" %>
      </div>
      <div class="form-group">
        <%= form.label :ทะเบียนรถ , class: 'label-control' %>
        <%= form.text_field :car , class:'form-control' , required: true , value: '-' %>
      </div>
      <div class="form-group">
        <%= form.label :วันที่สร้างเอกสาร , class:'label-control' %>
        <%= form.date_field :sent_date , class: 'form-control' , value: Time.now.strftime('%Y-%m-%d') , required: true %>
      </div>
      <div class="form-group">
        <%= form.label :หมายเหตุ , class: 'label-control' %>
        <%= form.text_area :remark , class: 'form-control' , placeholder: 'ระบุหมายเหตุเพิ่มเติม' , cols: 2, rows: 2 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <div class="form-group">
        <div class="row">
          <div class="col-sm-12">
            <%= form.submit ' บันทึกผล' , class: 'btn btn-success btn-rounded btn-block' %>
          </div>
          <div class="col-sm-12">
            <%= link_to ' ย้อนกลับ' ,  outbounds_path , class: 'btn btn-danger btn-rounded btn-block fa fa-backward' %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/outbounds/index.html.erb
<h1 class="text-center">จัดการ ป.58</h1>
<div class="row">
  <div class="col-sm-12">
    <div class="btn-group" role="group" aria-label="Basic example">
      <%= link_to ' หน้าหลัก' , home_path , class: 'btn btn-danger btn-lg fa fa-backward' %>
      <%= link_to ' สร้าง ป.58' , new_outbound_path , class: 'btn btn-success btn-lg fa fa-plus' %>
      <%= link_to ' ตรวจสอบ' , bags_path , class: 'btn btn-info btn-lg fa fa-search' %>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <div class="col-sm-12">
    <%= form_tag(outbounds_path , method: :get) do%>
    <div class="input-group mb-3">
      <%= text_field_tag(:search , params[:search] , class: 'form-control' , placeholder:'ค้นหาโดยหมายเลขเอกสาร' , size: 100) %>
      <div class="input-group-append">
        <%= submit_tag (" ค้นหา") , class: 'btn btn-info fa fa-search' %>
        <%= link_to "แสดงป.58 ทั้งหมด" , outbounds_path , class: 'btn btn-success' %>
      </div>
    </div>
    <% end %>
  </div>
</div>
<hr>
<div class="row">
  <% @outbounds.each do |outbound| %>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <strong>เลขที่เอกสาร : </strong><%= outbound.outbound_number %><br>
        <strong>ปลายทาง : </strong><%= outbound.destination %> <br>
        <strong>วัน/เวลาสร้างเอกสาร : </strong><%= outbound.sent_date.strftime("%d/%m/%C") %> <%= outbound.created_at.strftime("%H.%M") %><br>
        <strong>ชื่อผู้สร้าง : </strong><%= outbound.name_check %> <br>
        <strong>จำนวนถุง : </strong><%= outbound.count %> ถุง <br>
        <div class="btn-group" role="group">
          <%= link_to ' สแกน' , new_outbound_bag_path(outbound.id) , class: 'btn btn-success btn-sm fa fa-barcode' %>
          <%= link_to ' ข้อมูล' , outbound_path(outbound.id) , class:'btn btn-info btn-sm fa fa-info' %>
          <% if user_signed_in? %>
            <%= link_to ' ลบ' , outbound_path(outbound.id), class: 'btn btn-danger btn-sm fa fa-trash' , method: :delete , data: {confirm: "คุณแน่ใจที่จะลบ ป.58 หมายเลข #{outbound.outbound_number} ***การลบจะทำถุงใน ป.58 หมายเลขดังกล่าวถูกลบทั้งหมด ***" }  %>
          <% end %>
          <div class="dropdown show">
            <a class="btn btn-dark btn-sm fa fa-print" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              พิมพ์
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <%= link_to ' เรียงต้นทาง (3 แถว)' , prints_origin_path(outbound.id , 'pdf') , class: 'fa fa-print dropdown-item' , target:'_blank'%>&nbsp;&nbsp;
              <%= link_to ' เรียงปลายทาง(3 แถว)' , prints_destination_path(outbound.id , 'pdf') , class: 'fa fa-print dropdown-item' , target:'_blank'%>&nbsp;&nbsp;
              <%= link_to ' เรียงต้นทาง(1 แถว)' , paper_origin_path(outbound.id , 'pdf') , class:'fa fa-print dropdown-item' , target:'_blank ' %>&nbsp;&nbsp;
              <%= link_to ' เรียงปลายทาง(1 แถว)' , paper_destination_path(outbound.id ,'pdf') , class: 'fa fa-print dropdown-item' , target:'_blank'%>&nbsp;&nbsp;
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <div class="col-xs-12">
    <div class="text-center"><%= will_paginate @outbounds, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %></div>
  </div>
</div>

<script type="text/javascript">
  $('.dropdownMenuButton').dropdown()
</script>

app/views/outbounds/new.html.erb
<div class="col-lg-12">
  <h1 class="text-center">สร้าง ป.58</h1>
  <%= render 'form' %>
</div>

app/views/outbounds/paper_report.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= wicked_pdf_stylesheet_link_tag "report" %>
    <title>เอกสาร ป.58</title>
  </head>
  <body>
    <!-- Header -->
    <h6 class="text-right">เอกสาร ศป.นครสวรรค์</h6>
    <h4 class="text-center">บัญชีมอบหมายถุงไปรษณีย์ในประเทศ (ป.58)</h4>
    <h5 class="text-center"><u>กรณีไม่มีข้อมูลในระบบ TND</u></h5>

    <!-- outbound details -->
    <div class="card">
      <div class="card-body">
        <table class="table table-borderless table-sm">
          <tbody>
            <tr>
              <td style="height:1px"><strong>จาก : </strong><%= @outbound.origin %></td>
              <td style="height:1px"><strong>เลขที่เอกสาร : </strong><%= @outbound.outbound_number %></td>
              <td style="height:1px"><strong>ทะเบียนรถ : </strong><%= @outbound.car %></td>
            </tr>
            <tr>
              <td style="height:1px"><strong>ถึง : </strong><%= @outbound.destination %></td>
              <td style="height:1px"><strong>วันที่เอกสาร : </strong><%= @outbound.sent_date.strftime("%d/%m/%y") %></td>
              <td style="height:1px"><strong>เลขที่สายรัด : </strong><%= @outbound.strap %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <br>
    <table class="table table-bordered table-sm">
      <thead>
        <!-- thead 1 -->
        <th class="text-center" style="height:1px">ลำดับ</th>
        <th class="text-center" style="height:1px">หมายเลขป้ายปากถุง</th>
        <th class="text-center" style="height:1px">บริการ</th>
        <th class="text-center" style="height:1px">ต้นทาง</th>
        <th class="text-center" style="height:1px">ปลายทาง</th>
      </thead>
      <tbody>
        <% count = 0 %>
        <% @bags.each do |bag| %>
        <tr>
          <td class="text-center" style="height:1px"><%= count += 1 %></td>
          <td class="text-center" style="height:1px"><%= bag.number_check.upcase %></td>
          <td class="text-center" style="height:1px"><%= bag.service %></td>
          <td class="text-center" style="height:1px"><%= bag.origin %></td>
          <td class="text-center" style="height:1px"><%= bag.destination %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <!-- Summary -->
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="text-right doubleline"><strong>จำนวนถุงทั้งหมด : </strong><%= @bags.count %></p>
      </div>
    </div>

    <!--  Sign Name -->
    <table class="table table-borderless table-sm nobreak:before">
      <tr>
        <td style="height:1px"><strong>ลงชื่อผู้ส่งมอบ</strong>.................................</td>
        <td style="height:1px"><strong>ลงชื่อผู้ขนส่ง</strong>...................................</td>
        <td style="height:1px"><strong>ลงชื่อผู้รับมอบ</strong>.................................</td>
      </tr>
      <tr>
        <td style="height:1px">(.....................................................)</td>
        <td style="height:1px">(.....................................................)</td>
        <td style="height:1px">(.....................................................)</td>
      </tr>
      <tr>
        <td style="height:1px"><strong>ลงวันที่</strong>.......................<strong>เวลา</strong>..............</td>
        <td style="height:1px"><strong>ลงวันที่</strong>.......................<strong>เวลา</strong>..............</td>
        <td style="height:1px"><strong>ลงวันที่</strong>.......................<strong>เวลา</strong>..............</td>
      </tr>
    </table>
  </body>
</html>

app/views/outbounds/report.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= wicked_pdf_stylesheet_link_tag "report" %>
    <title>เอกสาร ป.58</title>
  </head>
  <body>
    <!-- Header -->
    <h6 class="text-right">เอกสาร ศป.นครสวรรค์</h6>
    <h5 class="text-center">บัญชีมอบหมายถุงไปรษณีย์ในประเทศ (ป.58)</h5>
    <h6 class="text-center"><u>กรณีไม่มีข้อมูลในระบบ TND</u></h6>

    <!-- outbound details -->
    <div class="card">
      <div class="card-body">
        <table class="table table-borderless table-sm">
          <tbody>
            <tr>
              <td style="height:1px"><strong>จาก : </strong><%= @outbound.origin %></td>
              <td style="height:1px"><strong>เลขที่เอกสาร : </strong><%= @outbound.outbound_number %></td>
              <td style="height:1px"><strong>ทะเบียนรถ : </strong><%= @outbound.car %></td>
            </tr>
            <tr>
              <td style="height:1px"><strong>ถึง : </strong><%= @outbound.destination %></td>
              <td style="height:1px"><strong>วันที่เอกสาร : </strong><%= @outbound.sent_date.strftime("%d/%m/%y") %></td>
              <td style="height:1px"><strong>เลขที่สายรัด : </strong><%= @outbound.strap %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <br>
    <table class="table table-bordered table-sm">
      <thead>
        <!-- thead 1 -->
        <th class="text-center" style="height:1px">#</th>
        <th class="text-center" style="height:1px">ป้ายปากถุง</th>
        <!-- thead 2 -->
        <th class="text-center" style="height:1px">#</th>
        <th class="text-center" style="height:1px">ป้ายปากถุง</th>
        <!-- thead 3 -->
        <th class="text-center" style="height:1px">#</th>
        <th class="text-center" style="height:1px">ป้ายปากถุง</th>
      </thead>
      <tbody>
        <% count = 0 %>
        <% @bags.each_slice(3) do |bags| %>
        <tr>
          <% bags.each do |bag| %>
            <td class="text-center" style="height:1px"><%= count+=1 %></td>
            <td class="text-center" style="height:1px"><%= bag.number_check.upcase %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <!-- Summary -->
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="text-right doubleline"><strong>จำนวนถุงทั้งหมด : </strong><%= @bags.count %></p>
      </div>
    </div>
    <!-- Sign Name -->
    <table class="table table-borderless table-sm nobreak:before">
      <tr>
        <td style="height:1px"><strong>ลงชื่อผู้ส่งมอบ</strong>.................................</td>
        <td style="height:1px"><strong>ลงชื่อผู้ขนส่ง</strong>...................................</td>
        <td style="height:1px"><strong>ลงชื่อผู้รับมอบ</strong>.................................</td>
      </tr>
      <tr>
        <td style="height:1px">(.....................................................)</td>
        <td style="height:1px">(.....................................................)</td>
        <td style="height:1px">(.....................................................)</td>
      </tr>
      <tr>
        <td style="height:1px"><strong>ลงวันที่</strong>.......................<strong>เวลา</strong>..............</td>
        <td style="height:1px"><strong>ลงวันที่</strong>.......................<strong>เวลา</strong>..............</td>
        <td style="height:1px"><strong>ลงวันที่</strong>.......................<strong>เวลา</strong>..............</td>
      </tr>
    </table>
  </body>
</html>

app/views/outbounds/show.html.erb
<h1 class="text-center">รายละเอียดบัญชี ป.58</h1>
  <div class="row">
    <div class="col-sm-12">
      <div class="btn-group" role="group">
        <%= link_to ' ย้อนกลับ' , outbounds_path , class: 'btn btn-danger fa fa-backward btn-sm'%>
        <%= link_to ' สแกน' , new_outbound_bag_path(@outbound.id) , class: 'btn btn-success fa fa-barcode btn-sm' %>
        <div class="dropdown show">
          <a class="btn btn-dark btn-sm fa fa-print" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            พิมพ์
          </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <%= link_to ' เรียงต้นทาง (3 แถว)' , prints_origin_path(@outbound.id , 'pdf') , class: 'fa fa-print dropdown-item' , target:'_blank'%>&nbsp;&nbsp;
            <%= link_to ' เรียงปลายทาง(3 แถว)' , prints_destination_path(@outbound.id , 'pdf') , class: 'fa fa-print dropdown-item' , target:'_blank'%>&nbsp;&nbsp;
            <%= link_to ' เรียงต้นทาง(1 แถว)' , paper_origin_path(@outbound.id , 'pdf') , class:'fa fa-print dropdown-item' , target:'_blank ' %>&nbsp;&nbsp;
            <%= link_to ' เรียงปลายทาง(1 แถว)' , paper_destination_path(@outbound.id ,'pdf') , class: 'fa fa-print dropdown-item' , target:'_blank'%>&nbsp;&nbsp;
          </div>
        </div>
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h6 class="card-title">รายละเอียด ป.58 เลขที่ <%= @outbound.outbound_number %></h6>
          <div class="card-text">
            <div class="row">
              <div class="col-sm-4">
                <strong>เลขที่ : </strong><%= @outbound.outbound_number %> <br>
                <strong>ต้นทาง : </strong><%= @outbound.origin %> <br>
                <strong>ปลายทาง: </strong><%= @outbound.destination %> <br>
                <strong>จำนวนถุงทั้งสิ้น </strong> <%= @outbound.count %> ถุง <br>
              </div>
              <div class="col-sm-4">
                <strong>วันที่เอกสาร : </strong><%= @outbound.sent_date.strftime("%d/%m/%y") %>  <br>
                <strong>เลขที่สายรัด : </strong><%= @outbound.strap %> <br>
                <strong>ทะเบียนรถ : </strong><%= @outbound.car %> <br>
                <strong>ชื่อผู้สร้าง : </strong><%= @outbound.name_check %>
              </div>
              <div class="col-sm-4">
                <strong>หมายเหตุ : </strong><%= @outbound.check_remark %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-bordered table-hover" id="outbounds">
                  <thead>
                    <th class="text-center">#</th>
                    <th class="text-center">ป้ายปากถุง</th>
                    <% if user_signed_in? %>
                      <th class="text-center"></th>
                    <% end %>
                  </thead>
                  <tbody>
                    <% count = 0 %>
                    <% @bags.each do |bag| %>
                    <tr>
                      <td class="text-center"><%= count += 1 %></td>
                      <td class="text-center"><%= bag.number_check.upcase%></td>
                      <% if user_signed_in? %>
                        <td class="text-center"><%= link_to ' ลบ' , bag_path(bag.id) , method: :destroy , data:{confirm: "คุณแน่ใจที่จะลบถุงหมายเลข #{bag.number_check}"}%></td>
                      <% end %>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <!-- pagination -->
            <div class="col-xs-12">
              <div class="text-center"><%= will_paginate @bags, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %></div>
            </div>
        </div>
      </div>
    </div>
  </div>
  </div>