config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  get 'home' , to: 'home#index'

  #Print Document
    # ปริ้นสามแถว
    get '/outbounds/:id/print/destination' , to: 'prints#show_destination' , as: 'prints_destination'
    get '/outbounds/:id/print/origin' , to: 'prints#show_origin' , as: 'prints_origin'
    # ปริ้นแถวเดียว
    get 'outbounds/:id/print/paper_destination' , to: 'prints#paper_show_destination' , as: 'paper_destination'
    get 'outbounds/:id/print/paper_origin' , to: 'prints#paper_show_origin' , as: 'paper_origin'

    # ปริ้น internals
    get '/internals/:id/print/internal' , to: 'prints#paper_internal' , as: 'paper_internal'

  get 'bags/' , to: 'bags#index'
  resources :bags
  resources :parcels
  resources :feedbacks
  resources :outbounds do
  	resources :bags
  end
  resources :internals do
    resource :parcels
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
	<div class="col-sm">
		<%= link_to  " จัดการ ป.58 (ใช้ส่งมอบถุง แผนก ลส.)" , outbounds_path , class: 'btn btn-success btn-lg btn-block fa fa-tasks'%>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-sm">
		<%= link_to " จัดการ ป.210 (ไว้ส่งมอบสิ่งของ)" , internals_path , class:'btn btn-info btn-lg btn-block fa fa-tasks' %>
	</div>
</div>
<hr>
<div class="row">
	<div class="col-sm">
		<%= link_to " แจ้งปัญหาการใช้งาน" , new_feedback_path , class:'btn btn-light btn-lg btn-block fa fa-comments' %>
	</div>
</div>
<hr>
<% if user_signed_in? %>
	<div class="row">
		<div class="col-sm">
			<%= link_to ' แสดงปัญหาการใช้งานทั้งหมด' , feedbacks_path , class: 'btn btn-primary btn-lg btn-block fa fa-comments' %>
		</div>
	</div>
<% end %>
<nav class="navbar fixed-bottom navbar-light bg-light">
	<%= link_to 'Administrator' , rails_admin_path %>
	<a href="https://github.com/game1095/postapp2020">	&copy;Develop by megamind</a>
</nav>