config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'
  get 'home' , to: 'home#index'

  #Print Document
    # ปริ้นสามแถว
    get '/outbounds/:id/print/destination' , to: 'prints#show_destination' , as: 'prints_destination'
    get '/outbounds/:id/print/origin' , to: 'prints#show_origin' , as: 'prints_origin'
    # ปริ้นแถวเดียว
    get 'outbounds/:id/print/paper_destination' , to: 'prints#paper_show_destination' , as: 'paper_destination'
    get 'outbounds/:id/print/paper_origin' , to: 'prints#paper_show_origin' , as: 'paper_origin'

    # ปริ้น internals
    get '/internals/:id/print/internal' , to: 'prints#paper_internal' , as: 'paper_internal'

  get 'bags/' , to: 'bags#index'
  resources :bags
  resources :parcels
  resources :feedbacks
  resources :outbounds do
  	resources :bags
  end
  resources :internals do
    resource :parcels
  end
end

app/models/internal.rb
class Internal < ApplicationRecord
  has_many :parcel , dependent: :destroy
  def internal_count
    self.parcel.count
  end
end

app/controllers/internals_controller.rb
class InternalsController < ApplicationController
  def index
    @internals = Internal.all.paginate(page: params[:page], per_page: 12).order(created_at: :desc)
  end

  def new
    @internal = Internal.new
  end

  def create
    @internal = Internal.create(internal_params)
    if @internal.save
      flash[:complete] = "ป.210 เลขที่ #{@internal.internal_number} ได้ถูกสร้างแล้ว ชื่อผู้สร้าง #{@internal.name}"
      redirect_to new_internal_parcels_path(@internal.id)
    else
      render 'new'
    end
  end

  def show
    @internal = Internal.find(params[:id])
    @parcels = Parcel.where(internal_id: @internal).sort_by(&:created_at).paginate(page: params[:page], per_page: 20)
  end

  def destroy
    @internal = Internal.find(params[:id])
    if @internal.destroy
      flash[:destroy] = "ป.210 เลขที่ #{@internal.internal_number} ได้ถูกลบแล้ว"
      redirect_to internals_path
    end
  end

  private
    def internal_params
      params.require(:internal).permit(:origin , :destination , :sent_date  , :internal_number , :name , :remark , :internal_number)
    end

end

app/helpers/internals_helper.rb
module InternalsHelper
end

app/views/internals/_form.html.erb
<%= form_for @internal do |form| %>
  <div class="row">
    <div class="col-sm-12">
      <div class="form-group">
        <%= form.label :เลขที่เอกสาร , class: 'label-control' %>
        <%= form.text_field :internal_number , class: ' form-control' , value: Time.now.strftime('%d%m%y')+rand(00000..99999).to_s , readonly: true %>
      </div>
      <div class="form-group">
        <%= form.label :แผนกต้นทาง , class: 'label-control'%>
        <%= form.text_field :origin , class:'form-control' , placeholder: 'ระบุแผนกต้นทาง' , required: true %>
      </div>
      <div class="form-group">
        <%= form.label :แผนกปลายทาง , class: 'label-control'%>
        <%= form.text_field :destination , class: 'form-control', placeholder: 'ระบุแผนกปลายทาง' , required: true  %>
      </div>
      <div class="form-group">
        <%= form.label :วันที่สร้างเอกสาร , class:'label-control' %>
        <%= form.date_field :sent_date , class: 'form-control' , value: Time.now.strftime('%Y-%m-%d') , required: true %>
      </div>
      <div class="form-group">
        <%= form.label :ชื่อผู้สร้าง , class: 'label-control' %>
        <%= form.text_field :name , class:'form-control' , required: true , placeholder: 'โปรดระบุชื่อ-สกุล เพื่อใช้ในการตรวจสอบ' %>
      </div>
      <div class="form-group">
        <%= form.label :หมายเหตุ , class: 'label-control' %>
        <%= form.text_area :remark , class: 'form-control' , placeholder: 'ระบุหมายเหตุเพิ่มเติม' , cols: 5, rows: 2 %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm">
      <div class="form-group">
        <div class="row">
          <div class="col-sm-6">
            <%= form.submit 'บันทึกผล' , class: 'btn btn-success btn-rounded btn-block' %>
          </div>
          <div class="col-sm-6">
            <%= link_to ' ย้อนกลับ' ,  internals_path , class: 'btn btn-danger btn-rounded btn-block fa fa-backward' %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/internals/index.html.erb
<h1 class="text-center">จัดการ ป.210</h1>
<div class="row">
  <div class="col-sm">
    <div class="form-group">
      <%= link_to ' กลับสู่หน้าหลัก' , home_path , class: 'btn btn-danger btn-lg fa fa-home' %>
      <%= link_to ' สร้าง ป.210' , new_internal_path , class: 'btn btn-success btn-lg fa fa-plus' %>
    </div>
  </div>
</div>
<hr>
<div class="row">
  <% @internals.each do |internal| %>
  <div class="col-sm-6">
      <div class="card">
        <div class="card-body">
          <strong>หมายเลขเอกสาร : </strong><%= internal.internal_number %> <br>
          <strong>ต้นทาง : </strong><%= internal.origin %> <br>
          <strong>ปลายทาง : </strong><%= internal.destination %> <br>
          <strong>วัน/เวลาสร้างเอกสาร : </strong><%= internal.sent_date.strftime("%d/%m/%C") %> <%= internal.created_at.strftime("%H.%M") %><br>
          <strong>ชื่อผู้สร้าง : </strong><%= internal.name %> <br>
          <strong>จำนวนสิ่งของ : </strong><%= internal.internal_count %><br>
          <div class="btn-group" role="group">
            <%= link_to ' สแกน' , new_internal_parcels_path(internal.id) , class: 'btn btn-success btn-sm fa fa-barcode' %>
            <%= link_to ' ข้อมูล' , internal_path(internal.id)  , class:'btn btn-info btn-sm fa fa-info' %>
            <% if user_signed_in? %>
              <%= link_to ' ลบ' , internal_path(internal.id), class: 'btn btn-danger btn-sm fa fa-trash' , method: :delete , data: {confirm: "คุณแน่ใจที่จะลบ ป.210 หมายเลข #{internal.internal_number} ***การลบจะทำถุงใน ป.210 หมายเลขดังกล่าวถูกลบทั้งหมด ***" }  %>
            <% end %>
            <%= link_to ' พิมพ์' , paper_internal_path(internal.id , 'pdf') , class: 'btn btn-dark btn-sm fa fa-print' , target:'_blank' %>
          </div>
        </div>
      </div>
  </div>
  <% end %>
</div>
<div class="col-xs">
  <div class="text-center"><%= will_paginate @internals, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %></div>
</div>

app/views/internals/new.html.erb
<div class="col-lg-12">
  <h1 class="text-center">สร้าง ป.210</h1>
  <%= render 'form' %>
</div>

app/views/internals/report.pdf.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <%= wicked_pdf_stylesheet_link_tag "report" %>
    <title>เอกสาร ป.58</title>
  </head>
  <body>
    <!-- Header -->
    <h6 class="text-right">เอกสาร ศป.นครสวรรค์</h6>
    <h4 class="text-center">บัญชีรับ - ส่งมอบ (ป.210)</h4>
    <h5 class="text-center"><u>กรณีไม่มีข้อมูลในระบบ TND</u></h5>

    <!-- outbound details -->
    <div class="card">
      <div class="card-body">
        <table class="table table-borderless table-sm">
          <tbody>
            <tr>
              <td style="height:1px"><strong>จากแผนก : </strong><%= @internal.origin %></td>
              <td style="height:1px"><strong>ถึงแผนก : </strong><%= @internal.destination %></td>
            </tr>
            <tr>
              <td style="height:1px"><strong>เลขที่เอกสาร : </strong><%= @internal.internal_number %></td>
              <td ><strong>วันที่เอกสาร : </strong><%= @internal.sent_date.strftime("%d/%m/%y") %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <br>
    <table class="table table-bordered table-sm">
      <thead>
        <!-- thead 1 -->
        <th class="text-center" style="height:1px">#</th>
        <th class="text-center" style="height:1px">หมายเลขส่งของ</th>
        <!-- thead 2 -->
        <th class="text-center" style="height:1px">#</th>
        <th class="text-center" style="height:1px">หมายเลขส่งของ</th>
        <!-- thead 3 -->
        <th class="text-center" style="height:1px">#</th>
        <th class="text-center" style="height:1px">หมายเลขส่งของ</th>
      </thead>
      <tbody>
        <% count = 0 %>
        <% @parcels.each_slice(3) do |bags| %>
        <tr>
          <% bags.each do |bag| %>
            <td class="text-center" style="height:1px"><%= count+=1 %></td>
            <td class="text-center" style="height:1px"><%= bag.parcel_number_check.upcase %></td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
    <!-- Summary -->
    <div class="panel panel-default">
      <div class="panel-body">
        <p class="text-right doubleline"><strong>จำนวนถุงทั้งหมด : </strong><%= @parcels.count %></p>
      </div>
    </div>
    <!-- Sign Name -->
    <table class="table table-borderless table-sm nobreak:before">
      <tr>
        <td style="height:1px"><strong>ลงชื่อผู้ส่งมอบ</strong>...........................................</td>
        <td style="height:1px"><strong>ลงชื่อผู้รับมอบ</strong>...........................................</td>
      </tr>
      <tr>
        <td style="height:1px">(....................................................................)</td>
        <td style="height:1px">(....................................................................)</td>
      </tr>
      <tr>
        <td style="height:1px"><strong>ลงวันที่</strong>............................<strong>เวลา</strong>..................</td>
        <td style="height:1px"><strong>ลงวันที่</strong>............................<strong>เวลา</strong>..................</td>
      </tr>
    </table>
  </body>
</html>

app/views/internals/show.html.erb
<h1 class="text-center">รายละเอียดบัญชี ป.210</h1>
  <div class="row">
    <div class="col-sm">
      <%= link_to ' ย้อนกลับ' , internals_path , class: 'btn btn-danger fa fa-backward'%>
      <%= link_to ' สแกน' , new_internal_parcels_path(@internal.id) , class: 'btn btn-success fa fa-barcode' %>
      <%= link_to ' พิมพ์เอกสาร' , paper_internal_path(@internal.id , 'pdf') , class: 'btn btn-dark fa fa-print' , target:'_blank' %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-sm">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">รายละเอียด ป.210 เลขที่ <%= @internal.internal_number %></h5>
          <div class="card-text">
            <div class="row">
              <div class="col-sm-4">
                <strong>เลขที่ : </strong><%= @internal.internal_number %> <br>
                <strong>ต้นทาง : </strong><%= @internal.origin %> <br>
                <strong>ปลายทาง: </strong><%= @internal.destination %> <br>
              </div>
              <div class="col-sm-4">
                <strong>วันที่เอกสาร : </strong><%= @internal.sent_date.strftime("%d/%m/%y") %>  <br>
                <strong>ชื่อผู้สร้าง : </strong><%= @internal.name %><br>
                <strong>จำนวนสิ่งของ : </strong><%= @internal.internal_count %>
              </div>
              <div class="col-sm-4">
                <strong>หมายเหตุ : </strong><%= @internal.remark %>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-12">
                <table class="table table-bordered table-hover" id="outbounds">
                  <thead>
                    <th class="text-center">เลขสิ่งของ</th>
                    <th class="text-center">ว/ด/ป เวลา ที่สแกน</th>
                  </thead>
                  <tbody>
                    <% count = 0 %>
                    <% @parcels.each do |parcel| %>
                    <tr>
                      <td class="text-center"><%= parcel.parcel_number_check.upcase%></td>
                      <td class="text-center"><%= parcel.created_at.strftime("%d/%m %H:%M:%S") %></td>
                      <% if user_signed_in? %>
                        <td class="text-center"><%= link_to ' ลบ' , parcel_path(parcel.id) , method: :destroy , data:{confirm: "คุณแน่ใจที่จะลบถุงหมายเลข #{parcel.number}"}%></td>
                      <% end %>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xs-12">
    <div class="text-center"><%= will_paginate @parcels, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %></div>
  </div>